name: Response tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests in devcontainer
        id: test
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/obdb/devcontainer
          push: never
          runCmd: |
            pytest tests/ --ignore=tests/schemas -xvs -n auto
